# Generated by Django 6.0.2 on 2026-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_gallery_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('fphone', models.CharField(max_length=15)),
                ('mphone', models.CharField(blank=True, max_length=15, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
