# Generated by Django 6.0.2 on 2026-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_studentregistration_remove_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
