# Generated by Django 6.0.2 on 2026-02-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_studentregistration_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='fphone',
            new_name='father_phone',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='mphone',
            new_name='mother_phone',
        ),
    ]
