# Generated by Django 6.0.2 on 2026-02-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_fphone_studentregistration_father_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='fname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='lname',
            new_name='Last_Name',
        ),
    ]
