# Generated by Django 6.0.2 on 2026-02-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_fname_studentregistration_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='father_phone',
            new_name='fphone',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='mother_phone',
            new_name='mphone',
        ),
    ]
