# Generated by Django 6.0.2 on 2026-02-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_father_phone_studentregistration_fphone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='fphone',
            new_name='Father_Phone',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='mphone',
            new_name='Mother_Phone',
        ),
    ]
